openapi: '3.0.2'
info:
    title: Crossfit WOD API
    version: '1.0.0'
servers:
    - url: http://localhost:3000/api/v1
paths:
    /api/v1/workouts:
        get:
            tags:
                - 'Workouts'
            parameters:
                - in: query
                  name: mode
                  schema:
                      type: string
                  description: The mode of a workout
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: string
                                        example: OK
                                    data:
                                        type: array
                                        # items:
                                        #   $ref: "#/components/schemas/Workout"
                '5XX':
                    description: FAILED
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: string
                                        example: FAILED
                                    data:
                                        type: object
                                        properties:
                                            error:
                                                type: string
                                                example: 'Some error message'
